drop table if exists users, items cascade;

CREATE TABLE  if not exists users (
  id integer generated by default as identity not NULL PRIMARY KEY,
  email varchar(200) not NULL unique,
  name varchar(200) not NULL

);

CREATE TABLE if not exists items (
  id integer generated by default as identity not NULL PRIMARY KEY,
  name varchar(200) not NULL,
  description varchar(200) not NULL,
  user_id integer not NULL,
  available boolean
);

ALTER TABLE items ADD FOREIGN KEY (user_id) REFERENCES users (id) on delete cascade;